apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goreplay-daemon
spec:
  selector:
    matchLabels:
      name: goreplay-daemon
  template:
    metadata:
      labels:
        name: goreplay-daemon
    spec:
      hostNetwork: true
      serviceAccountName: goreplay
      containers:
      - name: goreplay
        image: dwdraju/goreplay:2.0.0-rc2
        command:
          - "--input-raw k8s://deployments/nginx:80"
          - "--output-stdout"
