apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: goreplay-daemon
spec:
  selector:
    matchLabels:
      name: goreplay-daemon
  template:
    metadata:
      labels:
        name: goreplay-daemon
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: goreplay
      containers:
      - name: goreplay
        imagePullPolicy: Always
        image: dwdraju/goreplay
        command: ["./gor"]
        args: ["--input-raw", "k8s://goreplay/deployment/nginx:80", "--output-stdout", "--output-http", "http://httpd-service.goreplay.svc.cluster.local:80"]
